### ISSUE TITLE
wsapi.go:648:ChannelVoiceJoin() error waiting for voice to connect, timeout waiting for voice

### ISSUE THREAD

**Issue by jorgror** [Stieneee/mumble-discord-bridge#12]
Hi,
I saw your post on reddit and decided to give this a try. I run the bridge with docker. I did have to "guess" at some of the config parameters as I'm not familiar with discord bot API (GID, CID) and what permissions the bot needed (gave administrator) 

My current status is that the bot shows up as Online in discord and shows number of users from mumble as status. It does not show up in voice channels in either discord or mumble.

If I run bridge in mode=constant then I get this error in docker output.

2021/02/05 22:50:14 timeout waiting for voice
2021/02/05 22:50:14 Bridge died. Restarting
2021/02/05 22:50:14 Attempting to join Discord voice channel
2021/02/05 22:50:25 [DG1] wsapi.go:648:ChannelVoiceJoin() error waiting for voice to connect, timeout waiting for voice

I also tried running it in manual mode, but I got same error when I types !mumble-discord link (it was detected).

**Comment by stryan** [comment]
Sounds like you might have added the wrong GID and CID. GID means "Guild ID" and CID means "Channel ID". You can get those values by [enabling developer mode](https://discordia.me/en/developer-mode) and right clicking on the guild/channel and pressing "Copy ID". Double check those values and see if the issue occurs.

(FYI, here's what permissions I'm running my bot with)
- View Channels
- See Messages
- Read Message History
- Voice Channel Connect
- Voice Channel Speak
- Voice Channel Use Voice Activity

**Comment by jorgror** [comment]
Thanks! I had the wrong CID. Works now :)

**Comment by Rfvgyhn** [comment]
Just wanted to add that my bot works with only the following permissions:
* Voice Channel Connect
* Voice Channel Speak

**Comment by Stieneee** [comment]
@Rfvgyhn thanks for the input  I'm going to stick with @stryan's list as it covers some features you may not have tested. 

@jorgror glad you sorted it out you are not the only one that has had issues finding the Discord IDs, thanks for the contribution to the docs.
