### ISSUE TITLE
x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by HadetTheUndying** [Stieneee/mumble-discord-bridge#2]
I've had a horrible time getting Mumble to accept the SSL keypair i created for it and finally just commented it out, but it appears I can't connect the bot without it. Would it be too much to ask to offer an option to disable validating the cert?

**Comment by HadetTheUndying** [comment]
Should have checked the PR's this addresses the issue https://github.com/Stieneee/mumble-discord-bridge/pull/1

**Comment by Stieneee** [comment]
@HadetTheUndying I pushed the PR in a new release. Thanks for opening the issue.
