### ISSUE TITLE
Audio from Discord web client users is not be processed correctly

### ISSUE THREAD

**Issue by Stieneee** [Stieneee/mumble-discord-bridge#22]

**Comment by namtsui** [comment]
Yeah I see this bug, too. I wanted to test using linux as a sanity check.

android discord + linux bridge + linux murmurd: OK
web client discord + linux bridge + linux murmurd: mumble --> discord OK. discord --> mumble no audio and throws the same errors about
```
dgVoice: Error decoding opus data: invalid packet
dgVoice Error decoding opus data: buffer is too small
```
web client discord + openbsd bridge + openbsd umurmurd: same error

**Comment by Stieneee** [comment]
https://github.com/bwmarrin/discordgo/commit/7d7206b01bb53b2df6999691c19f2358a728b57a

**Comment by Stieneee** [comment]
After some digging this appears to be the fix.

https://github.com/bwmarrin/discordgo/commit/b18e1d72763cc67f7be5418b3be2471d7349afb0#diff-74522acf0f17ab66145d5d550513c9167dc20f264f49712f4913ab611074cde1
