### ISSUE TITLE
Default Mumble Channel

### ISSUE THREAD

**Issue by floridr** [Stieneee/mumble-discord-bridge#31]
Hi,

I love this tool. Unfortunately, the bridge reconnects from time to time for reasons still unknown. Fter reconned the brdige user goes into the root channel and not into the intended channel on the mumble server. Is it possible to define which channel the bridge automatically changes on the Mumble server?
I use it with Docker.

Cheers.

**Comment by stryan** [comment]
Either set the MUMBLE_CHANNEL environmental variable when running, or pass -mumble-channel "channel_name" as an argument.

You can see a list of all available settings by running mumble-discord-bridge --help.
